/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiRenderRouteImport } from './routes/api/render'
import { Route as ApiSpeechRouteImport } from './routes/api/speech'
import { Route as ApiVoicesRouteImport } from './routes/api/voices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderRoute = ApiRenderRouteImport.update({
  id: '/api/render',
  path: '/api/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeechRoute = ApiSpeechRouteImport.update({
  id: '/api/speech',
  path: '/api/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoicesRoute = ApiVoicesRouteImport.update({
  id: '/api/voices',
  path: '/api/voices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/api/files': typeof ApiFilesRoute
  '/api/render': typeof ApiRenderRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/voices': typeof ApiVoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/api/files': typeof ApiFilesRoute
  '/api/render': typeof ApiRenderRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/voices': typeof ApiVoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/api/files': typeof ApiFilesRoute
  '/api/render': typeof ApiRenderRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/voices': typeof ApiVoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/export'
    | '/api/files'
    | '/api/render'
    | '/api/speech'
    | '/api/voices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/export'
    | '/api/files'
    | '/api/render'
    | '/api/speech'
    | '/api/voices'
  id:
    | '__root__'
    | '/'
    | '/api/export'
    | '/api/files'
    | '/api/render'
    | '/api/speech'
    | '/api/voices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiRenderRoute: typeof ApiRenderRoute
  ApiSpeechRoute: typeof ApiSpeechRoute
  ApiVoicesRoute: typeof ApiVoicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render': {
      id: '/api/render'
      path: '/api/render'
      fullPath: '/api/render'
      preLoaderRoute: typeof ApiRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speech': {
      id: '/api/speech'
      path: '/api/speech'
      fullPath: '/api/speech'
      preLoaderRoute: typeof ApiSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voices': {
      id: '/api/voices'
      path: '/api/voices'
      fullPath: '/api/voices'
      preLoaderRoute: typeof ApiVoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExportRoute: ApiExportRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiRenderRoute: ApiRenderRoute,
  ApiSpeechRoute: ApiSpeechRoute,
  ApiVoicesRoute: ApiVoicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
