/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiVoicesRouteImport } from './routes/api/voices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoicesRoute = ApiVoicesRouteImport.update({
  id: '/api/voices',
  path: '/api/voices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/models': typeof ApiModelsRoute
  '/api/voices': typeof ApiVoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/models': typeof ApiModelsRoute
  '/api/voices': typeof ApiVoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/models': typeof ApiModelsRoute
  '/api/voices': typeof ApiVoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/models' | '/api/voices'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/models' | '/api/voices'
  id: '__root__' | '/' | '/api/models' | '/api/voices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiVoicesRoute: typeof ApiVoicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voices': {
      id: '/api/voices'
      path: '/api/voices'
      fullPath: '/api/voices'
      preLoaderRoute: typeof ApiVoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiVoicesRoute: ApiVoicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
